export const projectsData = {
  cards: [
    {
      id: 'frontview',
      title: 'FrontView',
      descr: `Front-view is a blog type application with
       reviews, posts, profiles, authorization,
        [rating, likes, dislikes, views, comments]`,
      imageSrc: 'assets/images/projects/frontview.png',
      extraImg: [
        'assets/images/projects/frontview-extra-1.png',
        'assets/images/projects/frontview-extra-2.png',
        'assets/images/projects/frontview-extra-3.png',
      ],
      techs: ['react','redux', 'ts', 'scss', 'mui', 'node', 'express', 'mongo'],
      date: '09.01.2023',
      link: 'https://frontview-kang.netlify.app/',
      ghlink: 'https://github.com/kang-front-dev/blog-app',
      isHot: true,
    },
    {
      id: 'ios-phone',
      title: 'IOS Phone App',
      descr: `A copy of the original IOS phone app with calls,
       contact list, recent messages and favorites, all information
        is stored in localStorage`,
      imageSrc: 'assets/images/projects/ios-phone.png',
      extraImg: [
        'assets/images/projects/ios-phone-extra-1.png',
        'assets/images/projects/ios-phone-extra-2.png',
        'assets/images/projects/ios-phone-extra-3.png',
      ],
      techs: ['html', 'scss', 'ts'],
      date: '28.09.2022.',
      link: 'https://ios-phone-app.netlify.app/',
      ghlink: 'https://github.com/kang-front-dev/ios-phone-app',
    },
    {
      id: 'momentum',
      title: 'Momentum',
      descr: `Momentum is a SPA web aplication with weather info(OWM API), clocks, custom music player and random quotes.
      There is also a background list with a parallax effect.
      `,
      imageSrc: 'assets/images/projects/momentum.png',
      extraImg: [
        'assets/images/projects/momentum-extra-1.png',
        'assets/images/projects/momentum-extra-2.png',
      ],
      techs: ['html', 'css', 'js'],
      date: '30.10.2021',
      link: 'https://kang-front-dev.github.io/momentum/',
      ghlink: 'https://github.com/kang-front-dev/momentum',
    },
    {
      id: 'christmass',
      title: 'Christmass',
      descr: `In this web-application i have implemented a sort and filter systems with search feature`,
      imageSrc: 'assets/images/projects/christmass.png',
      extraImg: ['assets/images/projects/christmass-extra-1.png'],
      techs: ['html', 'css', 'scss', 'js', 'ts'],
      link: 'https://kang-front-dev.github.io/christmass/App/dist/index.html',
      ghlink: 'https://github.com/kang-front-dev/christmass',
    },
    {
      id: 'artquiz',
      title: 'Art quiz',
      descr: `This is a SPA quiz game, different levels with random answers, progression and gallery, only in Russian.`,
      imageSrc: 'assets/images/projects/artquiz.png',
      techs: ['html', 'css', 'scss', 'js', 'ts'],
      link: 'https://kang-front-dev.github.io/art-quiz/art-quiz/',
      ghlink: 'https://github.com/kang-front-dev/art-quiz',
    },
    {
      id: 'funiro',
      title: 'Funiro',
      descr: `This is a landing page created using the slick Slider javascript library from a free template.
      
      `,
      imageSrc: 'assets/images/projects/funiro.png',
      extraImg: [
        'assets/images/projects/funiro-extra-1.png',
        'assets/images/projects/funiro-extra-2.png',
        'assets/images/projects/funiro-extra-3.png',
        'assets/images/projects/funiro-extra-4.png',
      ],
      techs: ['html', 'css', 'js'],
      date: '26.07.2021',
      link: 'https://kang-front-dev.github.io/funiro/',
      ghlink: 'https://github.com/kang-front-dev/funiro',
    },
    {
      id: 'infinity-road',
      title: 'Infinity Road',
      descr: `Endless road construction built on React.js`,
      videoSrc: `assets/video/video.mp4`,
      techs: ['html', 'scss', 'js', 'ts'],
      date: '11.11.2022',
      link: 'https://infinity-road.netlify.app/',
      ghlink: 'https://github.com/kang-front-dev/infinity-road',
    },
    {
      id: 'clocks',
      title: 'Slice clocks',
      descr: `Some future type clocks with interesting mechanics.`,
      imageSrc: 'assets/images/projects/clocks.png',
      techs: ['html', 'css', 'scss', 'js', 'ts'],
      link: 'https://kang-front-dev.github.io/aesthetic-clocks/',
      ghlink: 'https://github.com/kang-front-dev/aesthetic-clocks',
    },
    {
      id: 'pendulums',
      title: 'Pendulums',
      descr: `These Pendulums create an interesting illusion of hypnosis, animations are written in css.You can adjust the amount.`,
      imageSrc: 'assets/images/projects/pendulums.png',
      techs: ['html', 'css', 'scss', 'js', 'ts'],
      link: 'https://kang-front-dev.github.io/pendulums/',
      ghlink: 'https://github.com/kang-front-dev/pendulums',
    },
  ],
};
